feat header Component
Sang-geon-Wave/WhenThen-web pull request #1
Opened 2023-03-07 12:29 UTC by parkjs82

2023-03-07 12:50 UTC, c0510gy requested changes

2023-03-07 12:50 UTC, c0510gy commented on whenthen-web/src/components/headerComponent/index.tsx
> +const HeaderComponent: React.FunctionComponent<ProbsHeaderComponent> = ({}) => {
`HeaderComponent `에 넘겨주는 probs가 존재하나요? `ProbsHeaderComponent`가 필요하지 않아보이네요

2023-03-07 12:50 UTC, c0510gy commented on whenthen-web/src/pages/Landing/index.tsx
> +import HeaderComponent from '../../components/headerComponent';
Landing 페이지는 conflict 위험이 있으니 같은 페이지를 다루는 팀원들과 얘기하세요

2023-03-07 12:50 UTC, c0510gy commented on whenthen-web/src/components/headerComponent/index.tsx
> +  const isLogIn = true;
로그인 여부를 props로 받는건 어떤가요?
그리고 페이지를 제작할 때 Login Store를 하나 만들고, 해당 store에서 로그인정보를 가져오도록 변경할 수 있겠죠

2023-03-07 17:25 UTC, antifly55 commented
이건 당장 고칠 리뷰는 아니고 추후 논의 사항입니다.
header component, footer component 등은 거의 대부분에 페이지에서 많이 사용될 컴포넌트들입니다. 따라서 디렉토리명을 headerComponent로 하나로만 정해서 하기 보다, 공통적으로 기본 템플릿처럼 사용된다는 의미의 디렉토리명으로 변경이 되었으면 좋겠네요.

2023-03-07 17:28 UTC, antifly55 commented on whenthen-web/src/pages/Landing/index.tsx
> +import HeaderComponent from '../../components/headerComponent';
상건이형 말대로 우선 랜딩 페이지는 추후에 처리를 해야할 것 같습니다. 다음 미팅에서 여기를 어떤 방식으로 처리할지 결정하는게 좋을 것 같네요. (ex. router 등)

2023-03-09 10:49 UTC, parkjs82 commented on whenthen-web/src/components/headerComponent/index.tsx
> +  const isLogIn = true;
login store를 추가했지만 정상작동하지 않습니다

2023-03-09 10:49 UTC, parkjs82 commented on whenthen-web/src/pages/Landing/index.tsx
> +import HeaderComponent from '../../components/headerComponent';
롤백했습니다

2023-03-09 10:50 UTC, parkjs82 commented on whenthen-web/src/components/headerComponent/index.tsx
> +const HeaderComponent: React.FunctionComponent<ProbsHeaderComponent> = ({}) => {
probs를 지우고 login store의 isLogin으로 대체했습니다

2023-03-09 11:35 UTC, c0510gy requested changes

2023-03-09 11:35 UTC, c0510gy commented on whenthen-web/src/components/headerComponent/index.tsx
> +import React from 'react';
컴포넌트 디렉토리의 첫 글자는 대문자로 합시다. -> `HeaderComponent`

2023-03-09 11:35 UTC, c0510gy commented on whenthen-web/src/components/headerComponent/index.tsx
> +// }
쓰이지 않는 주석은 지우기

2023-03-09 11:35 UTC, c0510gy commented on whenthen-web/src/components/headerComponent/index.tsx
> +  const { LoginStore } = indexStore();
스토어 이렇게 불러쓰면 안되요, 그리고 스토어 이름 앞 소문자로

1. 루트 스토어 (rootStore)가 loginStore를 가지도록 만든다. (`src/stores/root.ts`)
2. `useRootData` 훅으로 부터 loginStore를 가져온다. (아래 커맨트 참고)

2023-03-09 11:35 UTC, c0510gy commented on whenthen-web/src/components/headerComponent/index.tsx
> +  }
화살표 함수로 통일합시다.

2023-03-09 11:35 UTC, c0510gy commented on whenthen-web/src/components/headerComponent/index.tsx
> +    screenClass: appStore.screenClass.get(),
여기에서 loginStore 참조하면 됩니다.

2023-03-09 11:35 UTC, c0510gy commented on whenthen-web/src/components/headerComponent/index.tsx
> +                height="40vh"
얘도 css로 빼면 좋을듯

2023-03-09 11:35 UTC, c0510gy commented on whenthen-web/src/components/headerComponent/index.tsx
> +            {LoginStore.isLogin === true ? (
boolean의 경우에는 `!!value` 또는 그냥 `value` 자체만으로 `true`랑 비교하는 효과를 얻을 수 있을 것

2023-03-09 11:35 UTC, c0510gy commented on whenthen-web/src/components/headerComponent/index.tsx
> +                height="40vh"
다른 태그들도 모두 마찬가지

2023-03-09 11:35 UTC, c0510gy commented on whenthen-web/src/components/headerComponent/indexStore.jsx
> +  LoginStore,
이 파일 삭제하고, `src/stores/app.ts` 에 있는 appStore 참조해서 loginStore 만들면 되요 `src/stores/login.ts` 로 두면 될듯

2023-03-09 11:35 UTC, c0510gy commented on whenthen-web/src/components/headerComponent/indexStore.jsx
> +  LoginStore,
그리고 얘는 왜 js파일이죠?

2023-03-09 11:35 UTC, c0510gy commented on whenthen-web/src/components/headerComponent/indexStore.jsx
> +  LoginStore,
그리고 jsx랑 js를 구분해서 사용해주세요

2023-03-09 11:35 UTC, c0510gy commented on whenthen-web/src/components/headerComponent/loginStore.jsx
> +
얘도 js네요
위 스토어 관련 커맨트 참조해서 이것도 다른 곳으로 옮기세요

2023-03-10 04:43 UTC, c0510gy commented
두개 컴포넌트 밖으로 빼세요

2023-03-10 04:46 UTC, c0510gy approved these changes
두개 컴포넌트 밖으로 빼고 머지하면 됩니다.

2023-03-10 04:48 UTC, merged