Feature/lay out component
Sang-geon-Wave/WhenThen-web pull request #11
Opened 2023-03-17 00:54 UTC by QueueMin

2023-03-17 01:40 UTC, c0510gy requested changes

2023-03-17 01:40 UTC, c0510gy commented on whenthen-web/src/components/HeaderComponent/index.tsx
> +                src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpaboC_OonRfowhuzgVIZ7BkLQYiWNeSQkfA&usqp=CAU"
이거 부트스트랩에서 제공하는 아이콘으로 대체합시다

2023-03-17 01:40 UTC, c0510gy commented on whenthen-web/src/components/LayOutComponent/DesktopDefault.module.scss
> +  // width: ;
?

2023-03-17 01:40 UTC, c0510gy commented on whenthen-web/src/components/LayOutComponent/MobileDefault.module.scss
> +  // width: ;
?

2023-03-17 01:40 UTC, c0510gy commented on whenthen-web/src/components/LayOutComponent/index.tsx
Layout은 컴포넌트가 아니라 레이아웃이에요!!
src/layouts/DefaultLayout 이런식으로 두라고 어딘가에 커맨트 했었던거 같은디

2023-03-17 01:40 UTC, c0510gy commented on whenthen-web/src/pages/LayoutTest/index.tsx
> +    <LayOutComponent
Layout은 props로 하위 컴포넌트를 받지 않아요. Inner content를 사용해서 하위 컴포넌트를 받기 바랍니다.

2023-03-18 01:48 UTC, c0510gy requested changes

2023-03-18 01:48 UTC, c0510gy commented on whenthen-web/src/stores/sideBar.ts
이건 appStore에 두세요, 따로 스토어를 팔 만큼 중요한 스토어가 아닙니다.

2023-03-18 01:48 UTC, c0510gy commented on whenthen-web/src/pages/LayoutTest/index.tsx
> +    <LayOutComponent
[https://developer-talk.tistory.com/226](https://developer-talk.tistory.com/226) 참고해서 수정하세요

2023-03-18 01:48 UTC, c0510gy commented on whenthen-web/src/components/LayOutComponent/index.tsx
> +  // }, [sideBarRef]);
안쓰는 주석 다 없애기

2023-03-18 01:48 UTC, c0510gy commented on whenthen-web/src/components/LayOutComponent/MobileDefault.module.scss
> +  // width: ;
안쓰는 주석 다 없애기

2023-03-18 01:48 UTC, c0510gy commented on whenthen-web/src/components/LayOutComponent/DesktopDefault.module.scss
> +  // width: ;
안쓰는 주석 다 없애기

2023-03-18 01:48 UTC, c0510gy commented on whenthen-web/src/components/HeaderComponent/index.tsx
> +  let SideBarButtonClicked = () => {
`let` -> `const`
`SideBarButtonClicked` -> `sideBarButtonClicked`

2023-03-18 01:48 UTC, c0510gy commented on whenthen-web/src/components/HeaderComponent/index.tsx
> +  let LogOutButtonClicked = () => {
`let` -> `const`
`LogOutButtonClicked` -> `logOutButtonClicked`

2023-03-18 01:48 UTC, c0510gy commented on whenthen-web/src/components/HeaderComponent/index.tsx
> +  let logInButtonClicked = () => {
`let` -> `const`

2023-03-18 11:31 UTC, parkjs82 commented on whenthen-web/src/components/HeaderComponent/index.tsx
> +                src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpaboC_OonRfowhuzgVIZ7BkLQYiWNeSQkfA&usqp=CAU"
교체완료

2023-03-18 11:31 UTC, parkjs82 commented on whenthen-web/src/components/LayOutComponent/DesktopDefault.module.scss
> +  // width: ;
없앰

2023-03-18 11:32 UTC, parkjs82 commented on whenthen-web/src/stores/sideBar.ts
이동함

2023-03-18 12:49 UTC, parkjs82 commented on whenthen-web/src/components/LayOutComponent/index.tsx
반영했음

2023-03-18 12:49 UTC, parkjs82 commented on whenthen-web/src/pages/LayoutTest/index.tsx
> +    <LayOutComponent
수정했는데 잘 된건지 봐주십셔

2023-03-18 13:28 UTC, c0510gy requested changes

2023-03-18 13:28 UTC, c0510gy commented on whenthen-web/src/components/HeaderComponent/index.tsx
> +    console.log(screenClass);
console.log 지우기

2023-03-18 13:28 UTC, c0510gy commented on whenthen-web/src/components/HeaderComponent/index.tsx
> +          onClick={() => sideBarButtonClicked()}
`onClick={sideBarButtonClicked}`

2023-03-18 13:28 UTC, c0510gy commented on whenthen-web/src/components/HeaderComponent/index.tsx
> +                log Out
Log out

2023-03-18 13:28 UTC, c0510gy commented on whenthen-web/src/components/HeaderComponent/index.tsx
>              src="https://pbs.twimg.com/profile_images/1121985451907137536/2Uq0Ih-2_400x400.jpg"
파일로 바꾸자!

2023-03-18 13:28 UTC, c0510gy commented on whenthen-web/src/components/HeaderComponent/index.tsx
> +              onClick={() => logInButtonClicked()}
`onClick={logInButtonClicked}`

2023-03-18 13:28 UTC, c0510gy commented on whenthen-web/src/layouts/DefaultDesktop/index.tsx
> +type Props = {
type -> interface
이름 개선

2023-03-18 13:28 UTC, c0510gy commented on whenthen-web/src/layouts/DefaultLayout/index.tsx
> +type Props = {
type -> interface
이름 개선

2023-03-18 13:28 UTC, c0510gy commented on whenthen-web/src/layouts/DefaultMobile/index.tsx
> +  const isDesktop = screenClass === 'xl';
필요없는듯

2023-03-18 13:28 UTC, c0510gy commented on whenthen-web/src/stores/app.ts
> +    isVisible: observable.box(false),
isVisible of what??
네이밍 개선 필요 -> sideBarVisibility

2023-03-18 13:28 UTC, c0510gy commented on whenthen-web/src/stores/app.ts
> +    changeSideBarState(data: boolean) {
changeSideBarVisibility

2023-03-18 13:28 UTC, c0510gy commented on whenthen-web/src/layouts/DefaultDesktop/index.tsx
> +  const isDesktop = screenClass === 'xl';
필요없는듯

2023-03-25 00:02 UTC, c0510gy requested changes
마지막으로 할 일:
1. 테스트 페이지 제거
2. 모든 페이지에 레이아웃 적용하기

2023-03-26 10:28 UTC, parkjs82 commented
고쳤숨당

2023-03-26 15:31 UTC, ty-kmu approved these changes

2023-03-27 12:23 UTC, c0510gy approved these changes

2023-03-27 13:27 UTC, merged