add: datepicker component
Sang-geon-Wave/WhenThen-web pull request #13
Opened 2023-03-23 10:22 UTC by yhdev7935

외부 요소 클릭시 datepicker 가 종료되는 것은 구현하지 못했음.

2023-03-23 13:29 UTC, ty-kim7 requested changes

2023-03-23 13:29 UTC, ty-kmu commented on whenthen-web/src/components/DatepickerComponent/index.tsx
> +      <input
디자인 일관성 있게 부트스트랩의 input으로 바꿔주세요.

2023-03-23 13:29 UTC, ty-kim7 commented on whenthen-web/src/components/DatepickerComponent/index.tsx
> +        }
지금 picker 외부 클릭시 닫히는건 구현 어려우면, 날짜 선택(클릭)시 picker도 숨겨지게 설정하는게 나을꺼 같아요.

2023-03-23 13:29 UTC, ty-kim7 commented on whenthen-web/src/components/DatepickerComponent/index.tsx
> +            ?.setAttribute('value', copy.toLocaleDateString())
워우 이게 무슨일이죠
input 태그에 value={ stateSomething } 로 설정하고, stateSometing을 Set 하는 방식으로 해주세요.

2023-03-23 13:29 UTC, ty-kim7 commented on whenthen-web/src/components/DatepickerComponent/index.tsx
> +    'December',
한국말로 합시당

2023-03-23 13:29 UTC, ty-kmu commented on whenthen-web/src/components/DatepickerComponent/index.tsx
> +interface PropsDatepickerComponent {}
probs에 선택한 날짜 YYYY-MM-DD로 저장해주시고,
export될수 있게 구현해주세요.
(페이지에서 값 가져와야됨)
ImageUploadComponent 참고 하면 될듯

2023-03-24 23:59 UTC, c0510gy requested changes

2023-03-24 23:59 UTC, c0510gy commented on whenthen-web/src/components/DatepickerComponent/index.tsx
> +const DateInformation = (now: Date, addMonth?: number) => {
이거 현재 DatepickerCompoenent에서만 쓰이는 함수니깐 함수 컴포 안에 두시고, 이름을 dateInformation과 같은 카멜 케이스로 바꾸되, 함수가 하고 있는 일을 더 잘 표현할 수 있는 이름으로 바꾸세요. (ex. addMonth(nowDate, month))

2023-03-24 23:59 UTC, c0510gy commented on whenthen-web/src/components/DatepickerComponent/index.tsx
> +  let last = new Date(copy);
얘네들도 네이밍 바꿔줘야 할듯.. copiedNow, firstDate, lastDate 이런식으로

2023-03-24 23:59 UTC, c0510gy commented on whenthen-web/src/components/DatepickerComponent/index.tsx
> +  let squares = [];
전반적으로 변수 이름들에 정보를 더 주고, 얘같은 경우는 `const`로 선언

2023-03-24 23:59 UTC, c0510gy commented on whenthen-web/src/components/DatepickerComponent/index.tsx
> +  let copy = new Date(now);
얘네들 웬지 const로 해도 될거 같은데..

2023-03-24 23:59 UTC, c0510gy commented on whenthen-web/src/pages/DatepickerPage/index.tsx
이 페이지는 머지 직전에 삭제

2023-03-27 17:05 UTC, yhdev7935 commented on whenthen-web/src/components/DatepickerComponent/index.tsx
> +    'December',
한국어로 하는 이유가 무엇인지용

2023-03-28 11:28 UTC, ty-kmu commented on whenthen-web/src/components/DatepickerComponent/index.tsx
> +    'December',
사이트 언어가 한국어니깐요?

2023-03-28 15:43 UTC, yhdev7935 commented on whenthen-web/src/components/DatepickerComponent/index.tsx
> +      <input
다음 commit에서 수정될 예정입니다.

2023-03-28 15:44 UTC, yhdev7935 commented on whenthen-web/src/components/DatepickerComponent/index.tsx
> +        }
다음 commit에서 수정될 예정입니다.

2023-03-28 15:45 UTC, yhdev7935 commented on whenthen-web/src/components/DatepickerComponent/index.tsx
> +            ?.setAttribute('value', copy.toLocaleDateString())
다음 commit에서 수정될 예정입니다.

2023-03-28 15:51 UTC, yhdev7935 commented on whenthen-web/src/components/DatepickerComponent/index.tsx
> +    'December',
다음 commit에서 수정될 예정입니다.

2023-03-28 16:24 UTC, yhdev7935 commented on whenthen-web/src/components/DatepickerComponent/index.tsx
> +  let last = new Date(copy);
다음 commit에서 수정될 예정입니다.

2023-03-28 16:37 UTC, yhdev7935 commented on whenthen-web/src/components/DatepickerComponent/index.tsx
> +const DateInformation = (now: Date, addMonth?: number) => {
일단, addMonth 대신 additionalMonth 로 바꾸긴 했습니다만.. 더 좋은 아이디어가 있으면 남겨주시길 바랍니다.

2023-03-28 16:38 UTC, yhdev7935 commented on whenthen-web/src/components/DatepickerComponent/index.tsx
> +  let copy = new Date(now);
다음 commit에서 수정될 예정입니다.

2023-03-28 16:38 UTC, yhdev7935 commented on whenthen-web/src/pages/DatepickerPage/index.tsx
머지 직전에 한번 더 commit 해서 제거하겠습니다.

2023-03-28 16:55 UTC, yhdev7935 commented on whenthen-web/src/components/DatepickerComponent/index.tsx
> +  let squares = [];
전체적으로 네이밍을 잘 못한 것은 알고 있지만,,, 아직도 마땅한 아이디어가 없네요.
`selectedDate` 는 `formattedDate`로,
`date`는 `nowDate` 로 변경하였습니다. 더 좋은 아이디어가 있다면 남겨주시면 감사하겠습니다.

2023-03-28 17:06 UTC, yhdev7935 commented on whenthen-web/src/components/DatepickerComponent/index.tsx
> +interface PropsDatepickerComponent {}
아직 감이 안 잡혀서 다음에 Page에 실제로 적용하는 작업할 때 추가하겠습니다.

2023-03-29 03:23 UTC, ty-kmu approved these changes

2023-03-30 05:56 UTC, ty-kmu approved these changes

2023-03-30 06:37 UTC, c0510gy approved these changes
테스트 페이지 제거후 머지

2023-03-30 06:37 UTC, c0510gy commented on whenthen-web/src/pages/DatepickerPage/index.tsx
머지전 삭제

2023-03-30 13:18 UTC, yhdev7935 commented on whenthen-web/src/pages/DatepickerPage/index.tsx
삭제완료했습니다.

2023-03-30 13:42 UTC, merged