Feature/landing page
Sang-geon-Wave/WhenThen-web pull request #17
Opened 2023-03-30 10:00 UTC by parkjs82

carousel은 형빈이가 내일 불참인 관계로 추후에 고치겟습니당

2023-03-30 10:11 UTC, c0510gy commented
conflict 해결되면 리뷰하겠습니다.

2023-03-30 13:43 UTC, SeokHyeon-Eom commented on whenthen-web/src/pages/Landing/index.tsx
> +import DefaultLayout from '../../layouts/DefaultLayout';
import DefaultLayout ... 2개입니다.

2023-03-30 13:43 UTC, SeokHyeon-Eom commented on whenthen-web/src/pages/Landing/index.tsx
>  import useRootData from '../../hooks/useRootData';
폴더 이름이 LangdingPage가 좋지 않을까요?

2023-04-02 04:32 UTC, SeokHyeon-Eom commented on whenthen-web/src/components/SideBarComponent/index.tsx
> +  function redirec(data: any) {
화살표 함수로 바꿔주세요. 불편하네요

2023-04-05 06:26 UTC, c0510gy requested changes

2023-04-05 06:26 UTC, c0510gy commented on whenthen-web/src/App.tsx
> -        <Route path="/login" element={<LoginPage />} />
이거 왜 없애는거임?

2023-04-05 06:26 UTC, c0510gy commented on whenthen-web/src/components/HeaderComponent/index.tsx
> +    navigate('/login');
`/login` 라우터 삭제하고 이게 되나??

2023-04-05 07:51 UTC, parkjs82 commented on whenthen-web/src/App.tsx
> -        <Route path="/login" element={<LoginPage />} />
conflict 없앨때 체크 안한듯
살려주시라요

2023-04-05 09:23 UTC, c0510gy approved these changes

2023-04-05 09:24 UTC, merged