Feature/signup page
Sang-geon-Wave/WhenThen-web pull request #18
Opened 2023-03-31 15:25 UTC by antifly55

라우팅 처리는 안한 상태여서 직접 테스트 하려면 App.tsx에 아래 코드 추가해야합니다. 

`<Route path="/signup" element={<SignupPage />} />`

간단하게 ID, Password, Password 확인만 추가했습니다.

2023-04-01 06:05 UTC, SeokHyeon-Eom commented on whenthen-web/src/components/SignupComponent/index.tsx
> +        <Form.Group className="mb-3" controlId="formBasicPassword">
controlId가 위에 비밀번호랑 같네요 controlId="formBasicPasswordRe"로 바꾸는게 어떨까요?

2023-04-03 09:22 UTC, antifly55 commented on whenthen-web/src/components/SignupComponent/index.tsx
> +        <Form.Group className="mb-3" controlId="formBasicPassword">
넵, 수정완료 하였습니다.

2023-04-05 05:09 UTC, SeokHyeon-Eom approved these changes
승인했습니다.

2023-04-05 06:34 UTC, c0510gy requested changes

2023-04-05 06:34 UTC, c0510gy commented on whenthen-web/src/components/SignupComponent/index.tsx
> +  const [signupErrType, setSignupErrType] = useState('');
`Type` 보다는 `Message` 로 부르는게 더 적합해보임

2023-04-05 06:34 UTC, c0510gy commented on whenthen-web/src/components/SignupComponent/index.tsx
> +  const [signupErrType, setSignupErrType] = useState('');
이 에러 메시지도 Enum으로 따로 파면 더 좋을듯

2023-04-05 06:34 UTC, c0510gy commented on whenthen-web/src/components/SignupComponent/index.tsx
> +  const [signupErr, setSignupErr] = useState(false);
위 에러 메시지를 Enum 타입으로 파면 에러 여부를 단순히 Enum 타입끼리의 비교연산으로 판단 가능 -> 이걸 달성하면 해당 state 제거

2023-04-05 06:34 UTC, c0510gy commented on whenthen-web/src/components/SignupComponent/index.tsx
> +  const [usrId, setUsrId] = useState('');
state 다 흩어져 있는거 user 타입 하나로 묶으면 더 좋을듯

2023-04-05 06:34 UTC, c0510gy commented on whenthen-web/src/components/SignupComponent/index.tsx
> +  const inputID = (event: React.ChangeEvent<HTMLInputElement>) => {
`inputID` -> `onChangeID` 

아래도 마찬가지

2023-04-05 06:34 UTC, c0510gy commented on whenthen-web/src/components/SignupComponent/index.tsx
> +  const [usrId, setUsrId] = useState('');
실제 DB에서 가져올 타입하고 통합하기 힘들면 (예를 들어, 비번 재입력 등 실제 user 타입엔 들어가지 않는 것이 존재) 그냥 SignUpFormType을 여기 파일에만 사용할 용도로 둬도 괜찮을듯

2023-04-07 21:50 UTC, c0510gy requested changes
코드 완성도를 극한으로 끌어올립시다!

2023-04-07 21:50 UTC, c0510gy commented on whenthen-web/src/components/SignupComponent/index.tsx
> +const enum errMsgTypes {
`SignupErrorMessages` 로 이넘 이름 변경

이넘은 타입의 개념과는 거리가 있음 (여기서는 에러 메시지를 일관되게 관리해주기 위함)

2023-04-07 21:50 UTC, c0510gy commented on whenthen-web/src/components/SignupComponent/index.tsx
> +  noID = '아이디를 입력해주세요',
이넘 안의 상수명은 대문자로 시작
아래도 동일하게 수정

2023-04-07 21:50 UTC, c0510gy commented on whenthen-web/src/components/SignupComponent/index.tsx
> +  const [signupErrMsg, setSignupErrMsg] = useState('');
앞서 선언한 이넘을 타입으로 가지도록

2023-04-07 21:50 UTC, c0510gy commented on whenthen-web/src/components/SignupComponent/index.tsx
> +  const [user, setUser] = useState({
유저 타입을 가지도록 변경
이후 개별 값 수정은 keyof를 이용 -> 해당 부분은 태윤이에게 물어보면 내가해준 리뷰 내용 참고 가능

2023-04-07 21:50 UTC, c0510gy commented on whenthen-web/src/components/SignupComponent/index.tsx
> +          {signupErrMsg !== '' && (
길이가 0인 문자열의 경우 `!==` 해줄 필요는 없음 (그냥 바로 &&으로 묶어도됨)

해당 state의 타입을 앞서 선언한 이넘타입 또는 null을 가지도록 구성하여 깔끔하게 구성 가능 (typescript에서 다양한 타입 선언 방식 참고)

2023-04-14 01:49 UTC, c0510gy requested changes
마지막 수정 요청일듯

2023-04-14 01:49 UTC, c0510gy commented on whenthen-web/src/components/SignupComponent/index.tsx
> +  const { screenClass, isLogin, changeLoginState } = useRootData(
`isLogin`, `changeLoginState` 안쓰이는거 지우기

2023-04-14 01:49 UTC, c0510gy commented on whenthen-web/src/components/SignupComponent/index.tsx
> +  };
updateSignupInfo 라는 함수를 따로 파고 key랑 value를 받도록 만들고, 이걸 id, pw, repw가 바뀔때 재사용하면 될듯

```
const updateSignupInfo = (
    key: keyof UserSignupType,
    value: string,
  ) => {
    setUser({
      ... user,
      [key]: value,
    });
  };
```
이후 `onChange={(e: React.ChangeEvent<HTMLInputElement>) => updateSignupInfo('ID', e.target.value)}` 이런식으로 재사용

2023-04-16 01:00 UTC, c0510gy approved these changes

2023-04-16 09:51 UTC, merged