Feature/timeline card componentes
Sang-geon-Wave/WhenThen-web pull request #2
Opened 2023-03-08 05:56 UTC by SeokHyeon-Eom

Do my best

2023-03-08 06:17 UTC, c0510gy requested changes

2023-03-08 06:17 UTC, c0510gy commented on whenthen-web/src/components/TimelineCardComponent/card.css
> +.mainBlock {
.css 사용하지 말고 .scss 사용하세요 `DesktopDefault.module.scss`

2023-03-08 06:17 UTC, c0510gy commented on whenthen-web/src/components/TimelineCardComponent/card.tsx
> +import React, { useState } from 'react';
card.tsx -> index.tsx 로 파일명변경하세요

2023-03-08 06:17 UTC, c0510gy commented on whenthen-web/src/components/TimelineCardComponent/card.tsx
> +import './card.css';
scss로 가져오세요 `import stylesDesktopDefault from './DesktopDefault.module.scss';`

2023-03-08 06:17 UTC, c0510gy commented on whenthen-web/src/components/TimelineCardComponent/card.tsx
> +  content,
props로 무조건 모든 값을 다 넣어줘야 할까요?
[https://kbwplace.tistory.com/158](https://kbwplace.tistory.com/158) 참고해서 필수로 넣지 않아도 되는 값들을 구분하면 좋을거 같네요

2023-03-08 06:17 UTC, c0510gy commented on whenthen-web/src/components/TimelineCardComponent/card.tsx
> +  const len: number = content.split('\n').length;
변수명 명확하게 바꿔주세요 예: `contentNumLines`

2023-03-08 06:17 UTC, c0510gy commented on whenthen-web/src/components/TimelineCardComponent/card.tsx
> +  const FS: number = 14;
마찬가지로 명확하게 바꿔주세요, 동시에 naming convention을 통일해주세요. (카멜케이스)

2023-03-08 06:17 UTC, c0510gy commented on whenthen-web/src/components/TimelineCardComponent/card.tsx
> +  let [more, detail] = useState(false);
네이밍 바꿔주세요. useState의 네이밍은 다음과 같은 형태로 합니다.
```
const [currentPageSize, setCurrentPageSize] = useState(pageSize);
```

2023-03-08 06:17 UTC, c0510gy commented on whenthen-web/src/components/TimelineCardComponent/card.tsx
> +  };
함수명도 컨벤션 맞춰주세요. 또한 해당 함수를 굳이 만들 필요는 없을것 같네요. 함수가 필요한 곳에 다음과 같이 붙이면 됩니다.
```
let [detailOpened, setDetailOpened] = useState(false);
setDetail(!detailOpened); // use this to toggle
```

2023-03-08 06:17 UTC, c0510gy commented on whenthen-web/src/components/TimelineCardComponent/card.tsx
> +      <div className="mainBlock">
css 클래스 명은 절대 문자열로 지정하지 마세요. MockComponent 참조하면 해당 부분 이해할 수 있습니다.

2023-03-08 06:17 UTC, c0510gy commented on whenthen-web/src/components/TimelineCardComponent/card.tsx
> +              marginRight: '1%',
이러한 스타일 설정은 최대한 css로 빼주면 좋습니다.

2023-03-08 06:17 UTC, c0510gy commented on whenthen-web/src/components/TimelineCardComponent/card.tsx
> +              marginRight: '1%',
커맨트 달지 않은 다른 부분들도 동일

2023-03-08 06:17 UTC, c0510gy commented on whenthen-web/src/components/TimelineCardComponent/card.tsx
> +                color: 'rgb(188, 188, 188)',
state에 따라 스타일이 다르게 지정될 때는 css에 두 가지 클래스를 두고, state값에 따라서 style을 다르게 참조하도록 하면 됩니다.

2023-03-08 06:17 UTC, c0510gy commented on whenthen-web/src/components/TimelineCardComponent/index.tsx
> +const TimelineCardComponent = () => {
이 컴포넌트는 뭐죠?
타임라인 컴포넌트는 다른사람이 진행하고 있지 않나요?

2023-03-08 06:17 UTC, c0510gy commented on whenthen-web/src/components/TimelineCardComponent/testData.tsx
> +var movie1 = {
이러한 test mock 데이터는 assets에 두는게 더 좋습니다. `assets/strings/TimeLineCardComponent/` 아래에 두세요

2023-03-08 06:17 UTC, c0510gy commented on whenthen-web/src/pages/MockPage/index.tsx
> +  //return <MockComponent message={'hello, world'} highlight={true} />;
conflict 발생할 수 있으니 해당 페이지는 수정하지 말아주세요

2023-03-08 09:50 UTC, parkjs82 commented on whenthen-web/src/components/TimelineCardComponent/card.tsx
> +                height: more ? `${FS * (len + 1.5)}px` : `${6 * FS}px`,
`min-height:` 를 사용하는것은 어떤가요?

2023-03-09 07:30 UTC, c0510gy approved these changes

2023-03-09 07:30 UTC, c0510gy commented on whenthen-web/src/assets/strings/TimeLineCardComponent/testData.tsx
> +var movie1 = {
.tsx 일 이유가 없어보이네요, .ts로 바꿔도 될거 같습니다.

그리고 해당 파일을 지금 사용하는 코드가 없는데, 페이지 제작할떄 쓸꺼죠? 이 가정 하에 머지 승인하겠습니다.

2023-03-09 07:43 UTC, SeokHyeon-Eom commented on whenthen-web/src/assets/strings/TimeLineCardComponent/testData.tsx
> +var movie1 = {
아직 수정부분이 있습니다. 마저 수정하고 PR을 다시 날린 이후에도 머지 승인이 떨어지면 머지하겠습니다

2023-03-09 12:31 UTC, c0510gy approved these changes

2023-03-09 12:31 UTC, c0510gy commented on whenthen-web/src/assets/strings/TimeLineCardComponent/testData.ts
> +let list: any[] = [movie1, movie2, movie3];
var 사용 금지, 모두 const로 바꾸기

2023-03-09 12:52 UTC, merged