Feature/create schedule page
Sang-geon-Wave/WhenThen-web pull request #20
Opened 2023-04-01 07:26 UTC by ty-kmu

일정 생성 페이지 추가
> 내용 편집 컴포넌트(텍스트 에디터)는 @xorud127 개발 완료후 적용 예정

2023-04-01 09:45 UTC, parkjs82 approved these changes
완벽해요!

2023-04-05 06:20 UTC, c0510gy requested changes

2023-04-05 06:20 UTC, c0510gy commented on whenthen-web/src/pages/CreateSchedulePage/index.tsx
> +    alert(JSON.stringify(createScFormValue, null, 2));
테스트 코드 삭제

2023-04-05 06:20 UTC, c0510gy commented on whenthen-web/src/pages/CreateSchedulePage/index.tsx
> +  const [createScFormValue, setCreateScFormValue] = useState({
1. 타입으로 만들기
2. 네이밍 변경 (object가 동사로 시작하는건 보기 좋지 않음)

2023-04-05 06:20 UTC, c0510gy commented on whenthen-web/src/pages/CreateSchedulePage/index.tsx
> +                      handleDateSelected('startDate', formattedDate)
이런식으로 string으로 키 전달하는거 다 없애고 타입 만들어서 ㄱㄱ

2023-04-06 09:12 UTC, ty-kmu commented on whenthen-web/src/pages/CreateSchedulePage/index.tsx
> +    alert(JSON.stringify(createScFormValue, null, 2));
삭제 완료

2023-04-06 09:12 UTC, ty-kmu commented on whenthen-web/src/pages/CreateSchedulePage/index.tsx
> +  const [createScFormValue, setCreateScFormValue] = useState({
1 , 2 수정완료

2023-04-07 01:27 UTC, c0510gy commented
핸들러 하나로 통일하세요~

2023-04-29 07:57 UTC, c0510gy approved these changes

2023-04-29 07:59 UTC, merged