Feature/text edit components
Sang-geon-Wave/WhenThen-web pull request #21
Opened 2023-04-01 13:55 UTC by xorud127

2023-04-05 06:42 UTC, c0510gy requested changes

2023-04-05 06:42 UTC, c0510gy commented on whenthen-web/src/App.tsx
> +        <Route path="/test" element={<TextPage />} />
머지 전 테스트 페이지 삭제

2023-04-05 06:42 UTC, c0510gy commented on whenthen-web/src/components/TextEditComponent/DesktopDefault.module.scss
> +  font-family: '나눔고딕딕';
나눔고"딕딕"?

2023-04-05 06:42 UTC, c0510gy commented on whenthen-web/src/components/TextEditComponent/index.tsx
> +  const [fontFamily, setFontFamily] = useState('나눔고딕');
폰트명 Enum 타입으로 만들기

2023-04-05 06:42 UTC, c0510gy commented on whenthen-web/src/components/TextEditComponent/index.tsx
> +  const [text, setText] = useState('');
이름 더 좋게 변경 `textContent` 라든지..

2023-04-05 06:42 UTC, c0510gy commented on whenthen-web/src/components/TextEditComponent/index.tsx
> +            <Dropdown.Item as="button" value={'나눔고딕'} onClick={handleFont}>
Enum으로 만든거 리스트 사용해서 코드 반복 삭제

예:
`[Font1, Font2, ...].map((font) => <Dropdown.Item as="button" value={font} onClick={handleFont}>font</Dropdown.Item>`

2023-04-05 06:42 UTC, c0510gy commented on whenthen-web/src/components/TextEditComponent/index.tsx
> +  const handleSetValue = (event) => {
무슨 value? 이름 바꾸기 예: `onChangeTextContent`

2023-04-05 06:42 UTC, c0510gy commented on whenthen-web/src/pages/testPage/index.tsx
삭제

2023-04-06 08:54 UTC, ty-kmu requested changes

2023-04-06 08:54 UTC, ty-kmu commented on whenthen-web/src/components/TextEditComponent/index.tsx
> +
컴포넌트 외부에서 데이터 가져올 수 있게 Props 등 구현

2023-04-06 08:54 UTC, ty-kmu commented on whenthen-web/src/components/TextEditComponent/index.tsx
> +const TextEditorComponent = () => {
폴더명이랑 컴포넌트명 일치 시켜주세요

2023-04-06 08:54 UTC, ty-kmu commented on whenthen-web/src/components/TextEditComponent/index.tsx
> +    console.log(event.target.innerHTML);
log 제거

2023-04-29 07:59 UTC, c0510gy commented
develop 현재 브랜치로 머지하고 충돌해결 필요

2023-04-29 11:42 UTC, c0510gy approved these changes
`package.json` 원래대로 해두고 머지

2023-05-01 03:09 UTC, ty-kmu approved these changes

2023-05-09 06:37 UTC, merged