Feature/timeline date components
Sang-geon-Wave/WhenThen-web pull request #3
Opened 2023-03-08 15:13 UTC by ty-kmu

plz review

2023-03-08 15:22 UTC, c0510gy requested changes

2023-03-08 15:22 UTC, c0510gy commented on whenthen-web/src/App.tsx
> +      <Route path="/timeline-date" element={<TimelineDatePage />} />
혹시 충돌 발생 가능하니 같은 페이지를 담당하는 사람에게 얘기를 해주세요

2023-03-08 15:22 UTC, c0510gy commented on whenthen-web/src/components/TimelineCardsComponent/index.tsx
> +  children: React.ReactNode;
리스트로 받는게 더 좋아보이긴 하네요 (의미적으로도)

2023-03-08 15:22 UTC, c0510gy commented on whenthen-web/src/components/TimelineCardsComponent/index.tsx
> +  children: React.ReactNode;
오잉 카드를 그냥 둘러싸는 컴포넌트였네요? 이게 필요한 이유가 뭐죠?

2023-03-08 15:22 UTC, c0510gy commented on whenthen-web/src/pages/TimelineDatePage/index.tsx
> +  let tmpDates = ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04'];
mock data긴 하지만 변경하지 않는 리스트이므로 const로 해주면 좋을거 같네요

2023-03-08 15:22 UTC, c0510gy commented on whenthen-web/src/pages/TimelineDatePage/index.tsx
> +import MockComponent from '../../components/MockComponent';
MockComponent는 그냥 여기서는 사용하지 맙시다

2023-03-09 01:52 UTC, parkjs82 commented on whenthen-web/src/pages/TimelineDatePage/index.tsx
> +
map으로 데이터를 불러오면 child를 여러개 만들지 않아도 될것 같아용

2023-03-09 01:52 UTC, parkjs82 commented on whenthen-web/src/components/TimelineDateComponent/index.tsx
> +      <div className={styles.timeline_date_card_title}>{date}</div>
카멜케이스로 할지 스네이크케이스로할지 논의가 필요해요

2023-03-09 05:30 UTC, ty-kmu commented on whenthen-web/src/App.tsx
> +      <Route path="/timeline-date" element={<TimelineDatePage />} />
넹

2023-03-09 05:34 UTC, ty-kmu commented on whenthen-web/src/pages/TimelineDatePage/index.tsx
> +  let tmpDates = ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04'];
변경 완료

2023-03-09 05:34 UTC, ty-kmu commented on whenthen-web/src/pages/TimelineDatePage/index.tsx
> +import MockComponent from '../../components/MockComponent';
삭제 완료

2023-03-09 05:34 UTC, ty-kmu commented on whenthen-web/src/components/TimelineDateComponent/index.tsx
> +      <div className={styles.timeline_date_card_title}>{date}</div>
카멜 케이스로 변경 했습니다

2023-03-09 07:24 UTC, c0510gy approved these changes

2023-03-09 09:24 UTC, ty-kim7 commented on whenthen-web/src/components/TimelineCardsComponent/index.tsx
> +  children: React.ReactNode;
구조를 변경하였습니다.

2023-03-09 09:25 UTC, ty-kim7 commented on whenthen-web/src/pages/TimelineDatePage/index.tsx
> +
불필요해서 삭제 처리하였습니다.

2023-03-09 11:12 UTC, merged