feat detect nowlocation
Sang-geon-Wave/WhenThen-web pull request #30
Opened 2023-04-30 14:11 UTC by parkjs82

2023-05-01 03:23 UTC, ty-kmu approved these changes

2023-05-01 03:25 UTC, ty-kmu requested changes

2023-05-01 03:25 UTC, ty-kmu commented on whenthen-web/src/components/SideBarComponent/DesktopDefault.module.scss
>    font-size: 150%;
폰트 사이즈는 rem em px 로 사용합시당

2023-05-01 13:17 UTC, c0510gy approved these changes

2023-05-02 01:46 UTC, ty-kmu approved these changes

2023-05-02 01:47 UTC, merged