add: introduction card component
Sang-geon-Wave/WhenThen-web pull request #7
Opened 2023-03-12 10:16 UTC by yhdev7935

2023-03-12 10:34 UTC, c0510gy requested changes

2023-03-12 10:34 UTC, c0510gy commented on whenthen-web/src/App.tsx
> +import IntroductionCardPage from './pages/IntroductionCardPage';
테스트페이지 commit 자체가 안된거로 보이는데, 이것도 삭제해야 할듯

2023-03-12 10:34 UTC, c0510gy commented on whenthen-web/src/components/IntroductionCardComponent/index.tsx
> +  // mobile style not exist
주석 삭제

2023-03-12 10:34 UTC, c0510gy commented on whenthen-web/src/components/IntroductionCardComponent/index.tsx
> +      <img className={styles.image} alt="No Image" src={imgUrl} />
`imgUrl`은 optional인데, 해당 값이 안주어질 경우를 처리해야 할듯

2023-03-12 10:35 UTC, yhdev7935 commented on whenthen-web/src/components/IntroductionCardComponent/index.tsx
> +      <img className={styles.image} alt="No Image" src={imgUrl} />
그럼 alt 로 처리되지 않나?

2023-03-12 10:40 UTC, c0510gy commented on whenthen-web/src/components/IntroductionCardComponent/index.tsx
> +      <img className={styles.image} alt="No Image" src={imgUrl} />
보통 이미지 안쓸때 No Image 글자가 뜨게하진 않지
`imgUrl && (컴포넌트)` 로 고치면 좋을듯

2023-03-12 10:41 UTC, c0510gy commented on whenthen-web/src/components/IntroductionCardComponent/index.tsx
> +      <img className={styles.image} alt="No Image" src={imgUrl} />
alt는 네트워크상 오류나 리소스가 어떤 이유로 삭제되었을 때 뜨도록 하는 역할

2023-03-12 16:14 UTC, c0510gy approved these changes

2023-03-13 02:21 UTC, antifly55 approved these changes

2023-03-13 02:21 UTC, antifly55 commented on whenthen-web/src/components/IntroductionCardComponent/index.tsx
> +  const styles = isDesktop ? stylesDesktopDefault : stylesDesktopDefault;
styles를 이렇게 삼항연산자로 정의한거는 나중에 반응형 레이아웃 구현하기 위해서 이렇게 한거죠?

2023-03-13 03:26 UTC, c0510gy commented on whenthen-web/src/components/IntroductionCardComponent/index.tsx
> +  const styles = isDesktop ? stylesDesktopDefault : stylesDesktopDefault;
그렇습니다

2023-03-13 05:03 UTC, merged