add: timeline page
Sang-geon-Wave/WhenThen-web pull request #8
Opened 2023-03-16 03:31 UTC by SeokHyeon-Eom

timeline page is coming

2023-03-16 03:52 UTC, c0510gy requested changes
예전 리뷰 데자뷰가 계속 보이는데, 리뷰 꼼꼼히 반영해주세요.

2023-03-16 03:52 UTC, c0510gy commented on whenthen-web/src/components/TimelineCardComponent/index.tsx
> +  const [more, detail] = useState(false);
뭔가 데자뷰같은 느낌인데, state 쓸때 네이밍은 [state, setState]입니다. 즉, 여기서는 [showDetail, setShowDetail] 이런식으로 붙일 수 있겠죠. [more, detail]은 무조건 고치세요.

2023-03-16 03:52 UTC, c0510gy commented on whenthen-web/src/components/TimelineCardComponent/index.tsx
>    content = '아직 정보가 없어요',
"아직 정보가 없어요"와 같은 string은 Enum type으로 따로 만들어서 사용하는게 좋습니다. DefaultContentEnum 타입으로 새로 만들면 되겠네요

2023-03-16 03:52 UTC, c0510gy commented on whenthen-web/src/components/TimelineCardComponent/index.tsx
>      if (more === false) detail(true);
boolean끼리 비교하지 않아도 됨

2023-03-16 03:52 UTC, c0510gy commented on whenthen-web/src/components/TimelineCardComponent/index.tsx
>      if (content === '아직 정보가 없어요') return;
개발자가 임의로 설정한 string끼리 비교하는거는 매우 좋지 않음. 앞서 얘기했던 enum 타입으로 만들면 해결될 문제.

2023-03-16 03:52 UTC, c0510gy commented on whenthen-web/src/components/TimelineCardComponent/index.tsx
>    const set_detail = () => {
네이밍 컨밴션 하나로 유지시켜주세요. 이것도 데자뷰같은데? 저번 리뷰가 제대로 반영된거 맞나요?

2023-03-16 03:52 UTC, c0510gy commented on whenthen-web/src/components/TimelineDateComponent/index.tsx
> +export default TimelineDateComponent;
이 컴포넌트는 왜 갑자기 등장한거죠? 이전 카드에서 만들어졌어야 했던거 아닌가?

2023-03-16 03:52 UTC, c0510gy commented on whenthen-web/src/components/TimelineDateComponent/index.tsx
> +      <br></br>
1. 내용이 아무것도 없으니 `<br />`로
2. style로 해결하고 이건 지우세요.

2023-03-16 03:52 UTC, c0510gy commented on whenthen-web/src/components/TimelineDateComponent/index.tsx
> +      {cards.map((val) => (
`val`과 같이 변수이름 만드는건 피하세요. `card`로 바꿀 것.

2023-03-16 03:52 UTC, c0510gy commented on whenthen-web/src/pages/TimelinePage/index.tsx
> +const TimelinePage: React.FunctionComponent<ProbsTimelinePage> = ({ data }) => {
페이지는 웬만해서는 props를 받지 않아요.

2023-03-16 03:52 UTC, c0510gy commented on whenthen-web/src/pages/TimelinePage/index.tsx
> +const TimelinePage: React.FunctionComponent<ProbsTimelinePage> = ({ data }) => {
일단 mock데이터로 채우세요.

2023-03-16 03:52 UTC, c0510gy commented on whenthen-web/src/pages/TimelinePage/index.tsx
> +  if (data === null) {
이걸꼭 null과 비교연산을 해줘야 할까요?

2023-03-16 03:52 UTC, c0510gy commented on whenthen-web/src/pages/TimelinePage/index.tsx
> +  data: ProbsTimelineDateComponent[];
네이밍 매우 좋지 않아요

2023-03-16 03:52 UTC, c0510gy commented on whenthen-web/src/pages/TimelinePage/index.tsx
> +import list from '../../assets/strings/TimeLinePage/testData';
네이밍 매우 좋지 않아요.

2023-03-16 03:52 UTC, c0510gy commented on whenthen-web/src/pages/TimelinePage/index.tsx
> +      {data.map((val) => (
네이밍좀 어떻게 해봐요..

2023-03-16 03:52 UTC, c0510gy commented on whenthen-web/src/assets/strings/TimeLinePage/testData.ts
> +const movie1 = {
얘네들 임의로 만드는거보다는 types 따로 만들어서 해당 타입을 갖는 mock data로 만들어주세요

2023-03-16 04:01 UTC, QueueMin commented on whenthen-web/src/components/TimelineCardComponent/index.tsx
>    content = '아직 정보가 없어요',
이거 개인적으로 신경쓰였던건데, Props 입니다. 뫀 페이지에서 Probs라고 되어있어서 다른 곳에서도 Probs라고 되어있는 곳들이 종종 보여서 Props로 고쳐주세양.

2023-03-16 04:03 UTC, c0510gy commented on whenthen-web/src/pages/TimelinePage/index.tsx
> +  data: ProbsTimelineDateComponent[];
그러고보니 여기도 Probs네 ㅋㅋ

2023-03-16 05:18 UTC, SeokHyeon-Eom commented on whenthen-web/src/components/TimelineDateComponent/index.tsx
> +export default TimelineDateComponent;
현재 timelineDateComponent에 임시로 만든 컴포넌트를 넣어나서 timelineCardComponent로 바꾸는 과정에서 생겼습니다. 이는 어떻게 수정할까요?

2023-03-16 08:40 UTC, c0510gy requested changes

2023-03-16 08:40 UTC, c0510gy commented on whenthen-web/src/assets/strings/TimeLinePage/testData.ts
> +}
타입 이름은 첫글자를 대문자로 해야됩니다
그리고 이거 여기에 두지 말고 `src/types/MovieData/index.ts` 로 옮기세요

2023-03-16 08:40 UTC, c0510gy commented on whenthen-web/src/components/TimelineCardComponent/index.tsx
> +}
0또는 1이 아니라, '아직 정보가 없어요'를 할당해줘야죠
```
enum DefaultEnum {
  DefaultText = "아직 정보가 없어요",
}
```

2023-03-16 08:40 UTC, c0510gy commented on whenthen-web/src/components/TimelineDateComponent/index.tsx
> +export default TimelineDateComponent;
그렇다면 이대로 두어도 될것 같습니다.

2023-03-16 08:40 UTC, c0510gy commented on whenthen-web/src/pages/TimelinePage/index.tsx
> +import timeLineMockDatas from '../../assets/strings/TimeLinePage/testData';
Data는 셀 수 없어서 Datas라는 단어는 존재하지 않습니다!

2023-03-17 00:05 UTC, c0510gy requested changes
타입에 관해서는 다음과 같이 처리하면 됩니다.
1. MovieItem 타입을 하나 만든다. (기존의 PropsTimelineCardComponent 타입)
2. MovieData (MovieItemsWithDate 같은게 더 좋은 이름같아 보임)의 cards (movieItems 가 더 좋은 이름같아 보임)가 MovieItem[] 타입을 가지도록 한다.
3. Props 타입이 MovieItem타입과 MovieData타입을 활용하게 하여 오류를 해결한다.

2023-03-17 00:05 UTC, c0510gy commented on whenthen-web/src/components/TimelineCardComponent/index.tsx
> +}
`defaultText` -> `DefaultText`

2023-03-17 00:05 UTC, c0510gy commented on whenthen-web/src/types/movieData/index.ts
> +export interface movieData {
**타입명 앞글자는 대문자로**

2023-03-17 00:05 UTC, c0510gy commented on whenthen-web/src/types/movieData/index.ts
> +  Date: string;
안에 attributes는 앞에 소문자로 시작

2023-03-17 13:19 UTC, c0510gy requested changes
1. `types/movieData` -> `types/MovieData`
2. `MovieData`의 `cards: PropsTimelineCardComponent[]` -> `movies: Movie[]` 로 변경
3. `types/Movie/index.ts` 만들고 거기에 `Movie` 타입 정의, 해당 타입에는 기존 Props에서 받던 정보가 들어가겠죠? (title, sub, imgUrl, content)
4. PropsTimelineDateComponent는 date, message, cards 대신 MovieData를 가진다.
5. PropsTimelineCardComponent는 title, sub, imgUrl, content 대신 Movie를 가진다.
6. 그럼 TimelineDateComponent에서 PropsTimelineCardComponent를 만들때 props로 MovieData 타입이 가지고 있는 Movie들을 props로 넘겨주면 된다.

2023-03-18 01:39 UTC, c0510gy approved these changes
types/movieData 를 types/MovieDataType 으로 변경했습니다.

2023-03-18 04:31 UTC, merged