Feature/create input components
Sang-geon-Wave/WhenThen-web pull request #9
Opened 2023-03-16 17:17 UTC by ty-kmu

2023-03-16 17:25 UTC, QueueMin reviewed
아는게 별로 없어서 리뷰를 적극적으로 땡기긴 힘드네용

2023-03-16 17:25 UTC, QueueMin commented on whenthen-web/src/components/LocationInputComponent/index.tsx
> +import DaumPostcode from 'react-daum-postcode';
얘가 뭐하는 애인지 궁금하네용

2023-03-16 17:27 UTC, ty-kmu commented on whenthen-web/src/components/LocationInputComponent/index.tsx
> +import DaumPostcode from 'react-daum-postcode';
아 Form과 InputGroup은 부트스트랩으로 UI 구성하려고 쓴거고,
DaumPostcode는 주소 검색할때 다음 우편 번호 검색창 띄울려고 쓴겁니당

2023-03-17 00:12 UTC, c0510gy requested changes

2023-03-17 00:12 UTC, c0510gy commented on whenthen-web/src/App.tsx
> +import CreatePage from './pages/CreatePage';
CreatePage 보단 CreateSchedulePage 등이 나을듯

2023-03-17 00:12 UTC, c0510gy commented on whenthen-web/src/components/LocationInputComponent/index.tsx
> +            `);
주소를 어따 반영하고, log나 주석은 지우기

2023-03-17 13:13 UTC, c0510gy approved these changes

2023-03-17 13:18 UTC, merged